//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportApp.WEB.Resourses.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1366184373_skoroportyaschiesya_gruzy {
            get {
                object obj = ResourceManager.GetObject("_1366184373_skoroportyaschiesya_gruzy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _234284 {
            get {
                object obj = ResourceManager.GetObject("_234284", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here will be posted information about exchange..
        /// </summary>
        public static string About_Exchange_en {
            get {
                return ResourceManager.GetString("About_Exchange_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет размещаться общая информация о бирже..
        /// </summary>
        public static string About_Exchange_ru {
            get {
                return ResourceManager.GetString("About_Exchange_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О бирже.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет размещаться краткое описание деятельности биржи.
        /// </summary>
        public static string AboutAppDescription {
            get {
                return ResourceManager.GetString("AboutAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довод.
        /// </summary>
        public static string AboutArg {
            get {
                return ResourceManager.GetString("AboutArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детализация довода.
        /// </summary>
        public static string AboutArgDescription {
            get {
                return ResourceManager.GetString("AboutArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что предлагает биржа.
        /// </summary>
        public static string AboutOurOffer {
            get {
                return ResourceManager.GetString("AboutOurOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет текст о бирже.
        /// </summary>
        public static string AboutPresentation {
            get {
                return ResourceManager.GetString("AboutPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string AddressDisplay {
            get {
                return ResourceManager.GetString("AddressDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле  {0}  должно быть заполнено.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Биржа транспортных перевозок.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap b8f3786f9f4e7b5f9a201dc1c1934e8c {
            get {
                object obj = ResourceManager.GetObject("b8f3786f9f4e7b5f9a201dc1c1934e8c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание вида деятельности.
        /// </summary>
        public static string BizDescriptionDisplay {
            get {
                return ResourceManager.GetString("BizDescriptionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование организации.
        /// </summary>
        public static string BizNameDisplay {
            get {
                return ResourceManager.GetString("BizNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле {0} должно быть заполнено.
        /// </summary>
        public static string BizNameRequired {
            get {
                return ResourceManager.GetString("BizNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус активности.
        /// </summary>
        public static string BizStatusDisplay {
            get {
                return ResourceManager.GetString("BizStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле  {0}  должно быть заполнено.
        /// </summary>
        public static string BizStatusRequired {
            get {
                return ResourceManager.GetString("BizStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уникальный номер налогоплательщика.
        /// </summary>
        public static string BizUniqueNumberDisplay {
            get {
                return ResourceManager.GetString("BizUniqueNumberDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле  {0}  должно быть заполнено.
        /// </summary>
        public static string BizUniqueNumberRequired {
            get {
                return ResourceManager.GetString("BizUniqueNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение {0} должно содержать {2} символов..
        /// </summary>
        public static string BizUniqueNumberValidation {
            get {
                return ResourceManager.GetString("BizUniqueNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связаться с поддержкой.
        /// </summary>
        public static string BtnGetInTouch {
            get {
                return ResourceManager.GetString("BtnGetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string BtnSend {
            get {
                return ResourceManager.GetString("BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальный объем, м3.
        /// </summary>
        public static string CapMax {
            get {
                return ResourceManager.GetString("CapMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальный объем, м3.
        /// </summary>
        public static string CapMin {
            get {
                return ResourceManager.GetString("CapMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место назначения.
        /// </summary>
        public static string CargoDestination {
            get {
                return ResourceManager.GetString("CargoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Габариты груза.
        /// </summary>
        public static string CargoDimentions {
            get {
                return ResourceManager.GetString("CargoDimentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы.
        /// </summary>
        public static string CargoesTitle {
            get {
                return ResourceManager.GetString("CargoesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр поиска грузов.
        /// </summary>
        public static string CargoFilter {
            get {
                return ResourceManager.GetString("CargoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место погрузки.
        /// </summary>
        public static string CargoLoadingPlace {
            get {
                return ResourceManager.GetString("CargoLoadingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск для пользователя.
        /// </summary>
        public static string CargoSearch {
            get {
                return ResourceManager.GetString("CargoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы биржи.
        /// </summary>
        public static string CargoTitle {
            get {
                return ResourceManager.GetString("CargoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог фирм.
        /// </summary>
        public static string CatalogTitle {
            get {
                return ResourceManager.GetString("CatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить изображение профиля.
        /// </summary>
        public static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любой город.
        /// </summary>
        public static string ChooseCity {
            get {
                return ResourceManager.GetString("ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любой регион.
        /// </summary>
        public static string ChooseRegion {
            get {
                return ResourceManager.GetString("ChooseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Населенный пункт.
        /// </summary>
        public static string CityNameDisplay {
            get {
                return ResourceManager.GetString("CityNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;Населенный пункт&apos;  должно быть заполнено.
        /// </summary>
        public static string CityNameRequired {
            get {
                return ResourceManager.GetString("CityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru.
        /// </summary>
        public static string Code2 {
            get {
                return ResourceManager.GetString("Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль и его подтверждение не совпадают.
        /// </summary>
        public static string ConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string ConfirmPasswordDisplay {
            get {
                return ResourceManager.GetString("ConfirmPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Artur Zhunusov,
        ///Kiseleva,
        ///220002, Minsk,
        ///Republic of Belarus     
        ///Phone:    
        ///Email: 
        ///.
        /// </summary>
        public static string Contact_Info_en {
            get {
                return ResourceManager.GetString("Contact_Info_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 220030, Республика Беларусь,
        ///г.Минск,
        ///ул. Кислева,
        ///Жунусов Артур     
        ///Тел.:    
        ///Email: 
        ///.
        /// </summary>
        public static string Contact_Info_ru {
            get {
                return ResourceManager.GetString("Contact_Info_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст сообщения.
        /// </summary>
        public static string ContactComment {
            get {
                return ResourceManager.GetString("ContactComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставьте свои контактные данные, и мы с вами обязательно свяжемся.
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г.Минск, Республика Беларусь.
        /// </summary>
        public static string ContactLocation {
            get {
                return ResourceManager.GetString("ContactLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна (местонахождения).
        /// </summary>
        public static string CountryNameDisplay {
            get {
                return ResourceManager.GetString("CountryNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;Страна (местонахождения)&apos;  должно быть заполнено.
        /// </summary>
        public static string CountryNameRequired {
            get {
                return ResourceManager.GetString("CountryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap defaultImage {
            get {
                object obj = ResourceManager.GetObject("defaultImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты.
        /// </summary>
        public static string EmailDisplay {
            get {
                return ResourceManager.GetString("EmailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан адрес электронной почты пользователя.
        /// </summary>
        public static string EmailExceptionUnknown {
            get {
                return ResourceManager.GetString("EmailExceptionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле {0}  должно быть заполнено.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле {0}  не содержит допустимый адрес электронной почты..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания периода.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обработке запроса произошла ошибка.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуги биржи.
        /// </summary>
        public static string ExchangeServicesTitle {
            get {
                return ResourceManager.GetString("ExchangeServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форум.
        /// </summary>
        public static string ForumTitle {
            get {
                return ResourceManager.GetString("ForumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет заголовок 1 слайда.
        /// </summary>
        public static string HeadSlide1 {
            get {
                return ResourceManager.GetString("HeadSlide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет заголовок 2 слайда.
        /// </summary>
        public static string HeadSlide2 {
            get {
                return ResourceManager.GetString("HeadSlide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет заголовок 3 слайда.
        /// </summary>
        public static string HeadSlide3 {
            get {
                return ResourceManager.GetString("HeadSlide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная страница.
        /// </summary>
        public static string IndexHeaderHomePage {
            get {
                return ResourceManager.GetString("IndexHeaderHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используйте учетную запись для входа.
        /// </summary>
        public static string LoginDescription {
            get {
                return ResourceManager.GetString("LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости биржи.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет размещаться содержимое панели .
        /// </summary>
        public static string PanelContent {
            get {
                return ResourceManager.GetString("PanelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель.
        /// </summary>
        public static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string PasswordDisplay {
            get {
                return ResourceManager.GetString("PasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введен неверный пароль.
        /// </summary>
        public static string PasswordExceptionIncorrect {
            get {
                return ResourceManager.GetString("PasswordExceptionIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле {0}  должно быть заполнено.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение {0} должно содержать не менее {2} символов..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap po_territorii_litvy_perevozyatsya_opasnye_gruzy {
            get {
                object obj = ResourceManager.GetObject("po_territorii_litvy_perevozyatsya_opasnye_gruzy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите наиболее подходящий для вас тарифный план .
        /// </summary>
        public static string PricingPaymentPlan {
            get {
                return ResourceManager.GetString("PricingPaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цены на услуги биржи.
        /// </summary>
        public static string PricingTitle {
            get {
                return ResourceManager.GetString("PricingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Область/Регион.
        /// </summary>
        public static string RegionNameDisplay {
            get {
                return ResourceManager.GetString("RegionNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &apos;Область/Регион&apos;  должно быть заполнено.
        /// </summary>
        public static string RegionNameRequired {
            get {
                return ResourceManager.GetString("RegionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string RegisterBtnTitle {
            get {
                return ResourceManager.GetString("RegisterBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создайте новую учетную запись.
        /// </summary>
        public static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня.
        /// </summary>
        public static string RememberMeDisplay {
            get {
                return ResourceManager.GetString("RememberMeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sborgruz {
            get {
                object obj = ResourceManager.GetObject("sborgruz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период поиска.
        /// </summary>
        public static string SeachPeriod {
            get {
                return ResourceManager.GetString("SeachPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите страну назначения.
        /// </summary>
        public static string SelectCountryDestination {
            get {
                return ResourceManager.GetString("SelectCountryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите страну отпраки.
        /// </summary>
        public static string SelectCountryDispatch {
            get {
                return ResourceManager.GetString("SelectCountryDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БТП.
        /// </summary>
        public static string ShortAppTitle {
            get {
                return ResourceManager.GetString("ShortAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shutterstock_135831281 {
            get {
                object obj = ResourceManager.GetObject("shutterstock_135831281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string SignInBtn {
            get {
                return ResourceManager.GetString("SignInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string SignOutBtn {
            get {
                return ResourceManager.GetString("SignOutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала периода.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поздравляем с успешной регистрацией.
        /// </summary>
        public static string SuccessfulRegistrationTitle {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая поддержка.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание 1 слайда.
        /// </summary>
        public static string TextSlide1 {
            get {
                return ResourceManager.GetString("TextSlide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание 2 слайда.
        /// </summary>
        public static string TextSlide2 {
            get {
                return ResourceManager.GetString("TextSlide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание 3 слайда.
        /// </summary>
        public static string TextSlide3 {
            get {
                return ResourceManager.GetString("TextSlide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транспорт.
        /// </summary>
        public static string TransportTitle {
            get {
                return ResourceManager.GetString("TransportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудники.
        /// </summary>
        public static string UserAccountEmployees {
            get {
                return ResourceManager.GetString("UserAccountEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все сотрудники.
        /// </summary>
        public static string UserAccountEmployeesAll {
            get {
                return ResourceManager.GetString("UserAccountEmployeesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о сотрудниках.
        /// </summary>
        public static string UserAccountEmployeesInfo {
            get {
                return ResourceManager.GetString("UserAccountEmployeesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои заявки.
        /// </summary>
        public static string UserAccountEntries {
            get {
                return ResourceManager.GetString("UserAccountEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявки на грузы.
        /// </summary>
        public static string UserAccountEntriesCargo {
            get {
                return ResourceManager.GetString("UserAccountEntriesCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявки на транспорт.
        /// </summary>
        public static string UserAccountEntriesTransport {
            get {
                return ResourceManager.GetString("UserAccountEntriesTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая информация.
        /// </summary>
        public static string UserAccountGeneral {
            get {
                return ResourceManager.GetString("UserAccountGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виды деятельности.
        /// </summary>
        public static string UserAccountGeneralActivities {
            get {
                return ResourceManager.GetString("UserAccountGeneralActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string UserAccountGeneralContacts {
            get {
                return ResourceManager.GetString("UserAccountGeneralContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документы.
        /// </summary>
        public static string UserAccountGeneralDoc {
            get {
                return ResourceManager.GetString("UserAccountGeneralDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочее.
        /// </summary>
        public static string UserAccountGeneralOther {
            get {
                return ResourceManager.GetString("UserAccountGeneralOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрационные данные.
        /// </summary>
        public static string UserAccountGeneralRegData {
            get {
                return ResourceManager.GetString("UserAccountGeneralRegData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщения.
        /// </summary>
        public static string UserAccountMessages {
            get {
                return ResourceManager.GetString("UserAccountMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входящие сообщения.
        /// </summary>
        public static string UserAccountMessagesIncoming {
            get {
                return ResourceManager.GetString("UserAccountMessagesIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходящие сообщения.
        /// </summary>
        public static string UserAccountMessagesOutgoing {
            get {
                return ResourceManager.GetString("UserAccountMessagesOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непрочитанные сообщения.
        /// </summary>
        public static string UserAccountMessagesUnread {
            get {
                return ResourceManager.GetString("UserAccountMessagesUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Партнеры.
        /// </summary>
        public static string UserAccountPartners {
            get {
                return ResourceManager.GetString("UserAccountPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступающие предложения партнерства.
        /// </summary>
        public static string UserAccountPartnersIncOffes {
            get {
                return ResourceManager.GetString("UserAccountPartnersIncOffes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои партнеры.
        /// </summary>
        public static string UserAccountPartnersMy {
            get {
                return ResourceManager.GetString("UserAccountPartnersMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходящие предложения партнерства.
        /// </summary>
        public static string UserAccountPartnersOutOffes {
            get {
                return ResourceManager.GetString("UserAccountPartnersOutOffes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личный кабинет пользователя.
        /// </summary>
        public static string UserAccountTitle {
            get {
                return ResourceManager.GetString("UserAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кабинет пользователя.
        /// </summary>
        public static string UserAreaTitle {
            get {
                return ResourceManager.GetString("UserAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный адрес электронной почты уже занят.
        /// </summary>
        public static string UserEmailExisted {
            get {
                return ResourceManager.GetString("UserEmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден.
        /// </summary>
        public static string UserExceptionNotFound {
            get {
                return ResourceManager.GetString("UserExceptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap viber {
            get {
                object obj = ResourceManager.GetObject("viber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальный вес, тонн.
        /// </summary>
        public static string WeightMax {
            get {
                return ResourceManager.GetString("WeightMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальный вес, тонн.
        /// </summary>
        public static string WeightMin {
            get {
                return ResourceManager.GetString("WeightMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whatsapp {
            get {
                object obj = ResourceManager.GetObject("whatsapp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zhunusovAvatar {
            get {
                object obj = ResourceManager.GetObject("zhunusovAvatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
